export const experienceData = [
  {
    date: 'Aug 2023 - Jul 2024',
    organization: 'Aeroidea',
    href: 'https://aeroidea.ru/',
    position: 'Frontend Engineer',
    description: [
      'Joined the team during the project design phase before the first MVP.',
      'Developed separate packages for design system components and helper functions, necessary for supporting multiple projects.',
      'Provided assistance and conducted code reviews for junior developers in the team.',
      'Implemented content creation functionality in the admin panel. Administrators could create various blocks (descriptions, sliders, product selections by category, event slides, and more).',
      'This allowed administrators to create unique pages for different events, promotions, and advertising campaigns, and remove them when no longer needed.',
      'This solution was also used for customizing advertising banners and promotions within the application.',
      'The application was built on Next.js. To optimize performance, a significant portion of backend requests was moved to the server-side, with some remaining on the client-side.',
      'Performed fine-tuning of page caching for faster page load times.',
      'Addressed the needs of users with disabilities: implemented themes with high contrast, as well as options for increasing font sizes and letter spacing.',
    ],
    chips: ['Next.js', 'zustand', 'TanStack Query', 'RTKQuery', 'mantine'],
  },
  {
    date: 'Feb 2022 - Sep 2023',
    organization: 'Zoftify',
    href: 'https://zoftify.com/',
    position: 'Frontend Engineer',
    description: [
      'Made significant contributions to the development of a web application using cutting-edge technologies and tools, including the Next.js framework. Actively involved in all stages of development, from design to implementation and optimization.',
      'Meticulously optimized bundle size and page loading speed, resulting in improved performance and user experience of the application.',
      'Created and customized administrative panels for both internal company projects and clients. The flexible and intuitive interface of the administrative panels allowed users to easily manage content and customize application settings.',
      'Actively participated in the development of an innovative application aimed at providing various specialized services such as massage, hairdressing, and more. This application demonstrates my ability to implement complex functional requirements and adapt to various business scenarios.',
      'In addition to core technologies like Stripe for payments, Chart.js for data visualization, and Tailwind for styling, I continuously strive to learn and implement new tools and approaches to ensure high quality and innovation in my work.',
    ],
    chips: ['Next.js', 'Tailwind', 'TypeScript', 'Redux-toolkit'],
  },
  {
    date: 'Jul 2020 - Feb 2022',
    position: 'Frontend Developer',
    href: 'https://www.helium10.com/',
    organization: 'Helium10',
    description: [
      'Provided support for large company projects and developed new ones.',
      "Developed the company's UI libraries and created a user interface for the Amazon seller app.",
      'Designed a system to monitor the history of goods prices, competitor prices, and set up advertising campaigns down to keywords. This enabled users to effectively manage their business on the Amazon platform and increase competitiveness.',
      "Contributed to the creation of a custom component library, including testing and documentation through a storybook. This ensured high quality and stability of the application's user interface.",
      'Participated in the development of tools for Amazon sellers (Adtomic), providing users with convenience and efficiency in sales on the platform.',
    ],
    chips: [
      'React.js',
      'Styled-component',
      'TypeScript',
      'zustand',
      're-atom',
      'Highcharts',
    ],
  },
  {
    date: 'Jan 2020 - Jul',
    organization: 'DeskAlert',
    position: 'Frontend Engineer',
    description:
      'Development of new functionality.Correction and work with the old code in the project. Switching the application to TypeScript',
    chips: ['React.js', 'SCSS', 'TypeScript', 'Redux', 'Material Ui'],
  },
]
