export const experienceData = [
  {
    key: 'zoftify',
    organization: 'Zoftify',
    href: 'https://zoftify.com/',
    chips: [
      'Next.js',
      'React',
      'TypeScript',
      'Tailwind',
      'Radix UI',
      'TanStack Query',
      'NestJS',
      'Prisma',
      'Stripe',
      'NextAuth',
    ],
  },
  {
    key: 'layers',
    organization: 'Layers',
    href: 'https://layers.md/',
    chips: [
      'React',
      'TypeScript',
      'Vite',
      'Mantine',
      'Zustand',
      'Redux Toolkit',
      'TanStack Query',
      'Lexical',
      'Playwright',
    ],
  },
  {
    key: 'schoolbusmanager',
    organization: 'School Bus Manager',
    href: 'https://www.schoolbusmanager.com/',
    chips: [
      'React',
      'TypeScript',
      'Vite',
      'Mantine',
      'Tailwind',
      'TanStack Query',
      'TanStack Router',
      'TanStack Table',
      'TanStack Virtual',
      'Zustand',
      'react-hook-form',
      'Zod',
      'Socket.IO',
      'MQTT',
      'Recharts',
      'i18next',
      'Playwright',
    ],
  },
  {
    key: 'aeroidea',
    organization: 'Aeroidea',
    href: 'https://aeroidea.ru/',
    chips: [
      'Next.js',
      'TypeScript',
      'Zustand',
      'TanStack Query',
      'RTK Query',
      'Mantine',
      'CSS',
    ],
  },
  {
    key: 'helium10',
    organization: 'Helium 10',
    href: 'https://www.helium10.com/',
    chips: [
      'React',
      'TypeScript',
      'Styled Components',
      'Zustand',
      'Reatom',
      'Highcharts',
    ],
  },
] as const
