import './globals.css'

import { Inter } from 'next/font/google'

import { ThemeProvider } from '@/widgets/providers/theme/ThemeProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // const cookieStore = cookies()

  return (
    <html lang={'en'} className={'dark'}>
      <body
        className={`${inter.className} overflow-x-hidden relative transition-all duration-500 dark:bg-mainBlue bg-white `}
      >
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  )
}
